apiVersion: v1
kind: Service
metadata:
  name: wisdompet-service
  namespace: wisdompet-namespace
  labels:
    app: wisdompet-app
spec:
  type: LoadBalancer
  selector:
    app: wisdompet-app-v2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
