apiVersion: v1
kind: Service
metadata:
  name: wisdompet-service
  namespace: wisdompet-namespace
  labels:
    app: wisdompet-app
spec:
  type: LoadBalancer
  selector:
    app: wisdompet-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisdompet-deployment-v2
  namespace: wisdompet-namespace
  labels:
    app: wisdompet-app-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisdompet-app-v2
  template:
    metadata:
      labels:
        app: wisdompet-app-v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: wisdompet
        image: lingxueli/wisdompet:latest-green
        ports:
        - containerPort: 8000
